# =============================================================================
# main-api-helm/templates/configmap.yaml
# =============================================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-config
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.app.name }}
    app.kubernetes.io/name: {{ .Values.app.name }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: {{ .Values.app.version }}
data:
  # Static values from values.yaml
  PORT: {{ .Values.config.port | quote }}
  AUXILIARY_SERVICE_URL: {{ .Values.config.auxiliaryServiceUrl | quote }}
  SERVICE_VERSION: {{ .Values.config.serviceVersion | quote }}
  
  # Dynamic values using templates
  NODE_ENV: {{ .Values.global.environment | quote }}
  ENVIRONMENT: {{ .Values.global.environment | quote }}