# =============================================================================
# main-api-helm/templates/networkpolicy.yaml
# =============================================================================
{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.app.name }}-network-policy
  namespace: {{ .Values.namespace.name }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.app.name }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: monitoring
    ports:
    - protocol: TCP
      port: {{ .Values.app.port }}
  - from: []
    ports:
    - protocol: TCP
      port: {{ .Values.app.port }}
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: auxiliary-service
    ports:
    - protocol: TCP
      port: 3001
  - to: []
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
{{- end }}