# =============================================================================
# main-api-helm/templates/vpa.yaml
# =============================================================================
{{- if .Values.vpa.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ .Values.app.name }}-vpa
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.app.name }}
  updatePolicy:
    updateMode: {{ .Values.vpa.updateMode | quote }}
  resourcePolicy:
    containerPolicies:
    - containerName: {{ .Values.app.name }}
      minAllowed:
        {{- toYaml .Values.vpa.minAllowed | nindent 8 }}
      maxAllowed:
        {{- toYaml .Values.vpa.maxAllowed | nindent 8 }}
      controlledResources: ["cpu", "memory"]
{{- end }}