apiVersion: v1
kind: ConfigMap
metadata:
  name: main-api-config
  namespace: main-api
  labels:
    app: main-api
data:
  NODE_ENV: "production"
  PORT: "3000"
  AUXILIARY_SERVICE_URL: "http://auxiliary-service.auxiliary-service.svc.cluster.local:3001"
  SERVICE_VERSION: "1.0.0"
  PROJECT_NAME: "microservices"
  ENVIRONMENT: "dev"