# k8s/service-accounts/main-api-service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: main-api-service-account
  namespace: main-api
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/microservices-dev-main-api-role
automountServiceAccountToken: true