# argocd/app-of-apps.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Einsteiniumeinsteinian/kantox-gitops
    targetRevision: HEAD
    path: argocd/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true  - repoURL: https://github.com/Einsteiniumeinsteinian/kantox-gitops.git
    targetRevision: HEAD
    path: argocd/applications
    directory:
      recurse: true
      include: 'argocd-ingress-application.yaml'
