apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
data:
  {{- if .Values.server.insecure }}
  server.insecure: "true"
  {{- end }}
  {{- if .Values.server.grpcWeb }}
  server.grpc.web: "true"
  {{- end }}
