apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: auxiliary-service-pdb
  namespace: auxiliary-service
  labels:
    app: auxiliary-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: auxiliary-service