apiVersion: v1
kind: ResourceQuota
metadata:
  name: auxiliary-service-quota
  namespace: auxiliary-service
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "16"
    persistentvolumeclaims: "4"
    services: "5"
    secrets: "10"
    configmaps: "10"