# k8s/service-accounts/auxiliary-service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auxiliary-service-account
  namespace: auxiliary-service
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/microservices-dev-auxiliary-service-role
automountServiceAccountToken: true
