apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: auxiliary-service-vpa
  namespace: auxiliary-service
  labels:
    app: auxiliary-service
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auxiliary-service
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: auxiliary-service
      minAllowed:
        cpu: 100m
        memory: 128Mi
      maxAllowed:
        cpu: 1
        memory: 1Gi
      controlledResources: ["cpu", "memory"]
