# =============================================================================
# auxiliary-service-helm/templates/rbac.yaml
# =============================================================================
{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.namespace.name }}
  name: {{ .Values.app.name }}-role
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.app.name }}-rolebinding
  namespace: {{ .Values.namespace.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace.name }}
roleRef:
  kind: Role
  name: {{ .Values.app.name }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
