# =============================================================================
# main-api-helm/templates/serviceaccount.yaml
# =============================================================================
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.app.name }}
    app.kubernetes.io/name: {{ .Values.app.name }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: {{ .Values.app.version }}
  annotations:
    # Dynamic IAM role ARN using template
    eks.amazonaws.com/role-arn: "arn:aws:iam::{{ .Values.global.accountId }}:role/{{ .Values.global.projectName }}-{{ .Values.global.environment }}-{{ .Values.app.name }}-role"
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}